ktor:
  application:
    modules:
      - me.dvyy.clicky.server.ApplicationKt.module
  deployment:
    port: 8080
site:
  # Root URL of the site, used for QR code
  url: ${SITE_URL:http://localhost:8080}
  # Global rate limit for all users, in requests per 10 seconds.
  rate_limit: ${SITE_RATE_LIMIT:100}
  chart:
    # Debounce time for chart updates in seconds (0 or less to disable.)
    update_interval: ${SITE_CHART_UPDATE_INTERVAL:0.2}
  # Time in hours after which inactive rooms are deleted, clients will be sent back to the homepage.
  inactive_room_timeout: ${SITE_INACTIVE_ROOM_TIMEOUT:24}