ktor:
    application:
        modules:
            - me.dvyy.me.dvyy.clicky.data.ApplicationKt.module
    deployment:
        port: 8080
        watch: [ classes ]
    development: true
site:
    url: http://localhost:8080